### PR TITLE
v1.0.0 release

### PR DESCRIPTION
**Pull request by Dreamwxve**
<h1 align="center">
Commits leading up to v1.0.0 release
</h1>

### CODE REVIEW

**Comment by Dreamwxve** [comment]
Still issues with logging in. When that is complete i will merge

**Comment by emilyrosette** [comment]
ETA on release?

**Comment by Dreamwxve** [comment]
soon 👀

**Comment by Dreamwxve** [comment]
<h2 align="center">
Verifying Nyxia
</h2>

**Pull request merged**
